name: my_calendar_app
description: A simple offline calendar with Hijri support, notifications, themes and an Android widget.
publish_to: "none"
version: 0.0.1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  table_calendar: ^3.0.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_local_notifications: ^12.0.4
  intl: ^0.18.0
  hijri: ^0.3.0
  shared_preferences: ^2.1.0
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true
